version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: serasa-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: serasa
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: serasa-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@serasa.local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  redis:
    image: redis:7
    container_name: serasa-redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
